language: go

go:
- 1.8

install:
- go get -v github.com/Masterminds/glide
- cd $GOPATH/src/github.com/Masterminds/glide
- go install && cd -
- glide install
- go get -t -v ./...

script:
- cd pkg
- rake test