language: go

go:
- 1.8

install:
  - export GOPATH="${TRAVIS_BUILD_DIR}/vendor/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/vendor/_workspace/bin:$PATH"

script:
- cd pkg
- go test ./... -v